### ISSUE TITLE
W3C validation errors

### ISSUE THREAD

**Issue by yitwail** [g-kanoufi/genesis-material-design-lite-child-theme#1]
When I run the W3C Validator -- https://validator.w3.org/ -- on the demo located at http://demo-mdl.lostwebdesigns.com/ there are a fair number of errors. Any chance some of them can be addressed?

I think your child theme is otherwise terrific.

Regards,
John K

**Comment by g-kanoufi** [comment]
Hi John,

The last push fixes the Validator Errors, i will update the demo tomorrow, so it will also be fixed there.
Thank you for checking on this and sharing it with me.

Feel free to "Star" this repository if you like the child theme and use it.

Cheers,

## 

Guillaume

**Comment by yitwail** [comment]
Guillaume,

Thanks for the quick response. I'm eager to try out your child theme in my next Genesis project.

**Comment by g-kanoufi** [comment]
John,

Feel free to send me the link to your project once it's done, it makes me very happy to know this child theme will be used by other people.

Cheers.
