### ISSUE TITLE
Fail on gulp

### ISSUE THREAD

**Issue by dianjuar** [g-kanoufi/genesis-material-design-lite-child-theme#2]
Hello. I tried run `gulp` to change the color palette but a lot of errors appear, try to fix a lot of them by changing the packages, node and gulp version without success... Have you tried to run gulp recently?

**Comment by g-kanoufi** [comment]
Hi,

Thank you for the update, i guess i am in for making a new gulpfile. Will try to update this soon.

**Comment by g-kanoufi** [comment]
Updated the gulpfile to the excellent WPGULP, :)
