### ISSUE TITLE
Gulp detecting changes but not refreshing the browser

### ISSUE THREAD

**Issue by dianjuar** [g-kanoufi/genesis-material-design-lite-child-theme#3]
Hello again.

When running gulp and make some changes on scss the css is generated fine but the browser live reload is not working.

Does it work for you ?

**Comment by g-kanoufi** [comment]
Hi there,

It seems to me that it works as it should, are you editing any of the scss files inside the styles folder?
If you still have issues, please take a look at the wpGulp documentation, and your gulpfile if you changed it.

**Comment by dianjuar** [comment]
Yes, the changed files are inside the `styles` folder. I will check what you are referring to solve the problem

**Comment by dianjuar** [comment]
Nope... The problem still there...
At the end just ignore the fact that doesn't reload the browser, I did it manually

**Comment by g-kanoufi** [comment]
Very strange as it seems to work as expected( auto reload or just update of the css ) with browsersync.
I'll close this as i can't reproduce.

Thanks
