### ISSUE TITLE
Load Roboto fonts form https

### ISSUE THREAD

**Issue by dianjuar** [g-kanoufi/genesis-material-design-lite-child-theme#4]
Hi I deployed your theme in a https server and the browser throw me the message 

_"This page is trying to load scripts from unauthenticated sources"_

![image](https://user-images.githubusercontent.com/7026066/32762635-84493fe6-c8c8-11e7-9d54-63071e829da0.png)

Checking the console this was caused by loading the roboto form using just http not httpS.

**Comment by g-kanoufi** [comment]
Fixed in pull request #5
